project:
  type: website
  output-dir: docs

website:
  title: "Cultural Health Connect"
  navbar:
    background: "#103d79"
    logo: Images/CHChug.png
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      #- text: "Programs"
        #href: Programs.html
      - text: "Contact"
        href: Contact.html
      #- text: "Donate"
        #href: Donate.html

format:
  html:
    theme: default
    css: styles.css
    toc: false