project:
  type: website
  output-dir: docs

website:
  title: "Cultural Health Connect"
  navbar:
    background: "#004D40"
    logo: images/logo.png
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - text: "Programs"
        href: programs.html
      - text: "Contact"
        href: contact.html
      - text: "Donate"
        href: donate.html

format:
  html:
    theme: default
    css: styles.css
    toc: false
